### ISSUE TITLE
cannot login

### ISSUE THREAD

**Issue by kinouzero** [managemeals/manage-meals-api#12]
Hi,

I use this docker compose, but impossible to login, there is no error in logs.
I use with my valkey and mongodb instance I already have.

```yml
  manage-meals-api:
    <<: [*basic, *network-zero, *restart-always]
    container_name: ${MANAGE_MEALS_API_NAME}
    depends_on:
      - ${MANAGE_MEALS_SCRAPER_NAME}
      - ${MANAGE_MEALS_SEARCH_SYNC_NAME}
      - ${MONGODB_NAME}
      - ${TYPESENSE_NAME}
      - ${VALKEY_NAME}
    environment:
      ACCESS_JWT_SECRET: ${MANAGE_MEALS_JWT_ACCESS_SECRET}
      AUTH_ACCESS_TOKEN_EXPIRE_SEC: ${MANAGE_MEALS_AUTH_ACCESS_TOKEN_EXPIRE_SEC}
      AUTH_REFRESH_TOKEN_EXPIRE_SEC: ${MANAGE_MEALS_AUTH_REFRESH_TOKEN_EXPIRE_SEC}
      MONGO_DB: ${MANAGE_MEALS_DB}
      MONGO_URL: ${MONGODB_URL}
      RECIPE_SCRAPER_URL: ${MANAGE_MEALS_SCRAPER_URL}
      REDIS_URL: ${VALKEY_URL}
      REFRESH_JWT_SECRET: ${MANAGE_MEALS_JWT_REFRESH_SECRET}
      TYPESENSE_API_KEY: ${TYPESENSE_API_KEY}
      TYPESENSE_HOST: ${TYPESENSE_NAME}
      TYPESENSE_PORT: ${TYPESENSE_PORT}
      USER_REGISTER_ENABLED: ${TRUE}
    image: ghcr.io/managemeals/manage-meals-api:${LATEST_VERSION}
    labels:
      <<: *label-wud-latest
      wud.display.icon: 'sh-mealie'
      wud.display.name: 'ManageMeals API'
      wud.link.template: 'https://github.com/managemeals/manage-meals-api/pkgs/container/manage-meals-api'
    volumes:
      - ${DIR_LOCALTIME}:${DIR_LOCALTIME}:ro

  manage-meals-scraper:
    <<: [*basic, *network-zero, *restart-always]
    container_name: ${MANAGE_MEALS_SCRAPER_NAME}
    image: ghcr.io/managemeals/manage-meals-scraper:${LATEST_VERSION}
    labels:
      <<: *label-wud-latest
      wud.display.icon: 'sh-mealie'
      wud.display.name: 'ManageMeals Scraper'
      wud.link.template: 'https://github.com/managemeals/manage-meals-api/pkgs/container/manage-meals-scraper'
    volumes:
      - ${DIR_LOCALTIME}:${DIR_LOCALTIME}:ro

  manage-meals-search-sync:
    <<: [*basic, *network-zero, *restart-always]
    container_name: ${MANAGE_MEALS_SEARCH_SYNC_NAME}
    depends_on:
      - ${MONGODB_NAME}
      - ${TYPESENSE_NAME}
    environment:
      MONGO_DB: ${MANAGE_MEALS_DB}
      MONGO_URL: ${MONGODB_URL}
      TYPESENSE_API_KEY: ${TYPESENSE_API_KEY}
      TYPESENSE_HOST: ${TYPESENSE_NAME}
      TYPESENSE_PORT: ${TYPESENSE_PORT}
    image: ghcr.io/managemeals/manage-meals-search-sync:${LATEST_VERSION}
    labels:
      <<: *label-wud-latest
      wud.display.icon: 'sh-mealie'
      wud.display.name: 'ManageMeals Search Sync'
      wud.link.template: 'https://github.com/managemeals/manage-meals-api/pkgs/container/manage-meals-search-sync'
    volumes:
      - ${DIR_LOCALTIME}:${DIR_LOCALTIME}:ro

  manage-meals-web:
    <<: [*basic, *network-zero, *restart-always]
    container_name: ${MANAGE_MEALS_WEB_NAME}
    depends_on:
      - ${MANAGE_MEALS_API_NAME}
    environment:
      API_URL: ${MANAGE_MEALS_API_URL}
      BODY_SIZE_LIMIT: ${MANAGE_MEALS_BODY_SIZE_LIMIT}
      COOKIE_ACCESS_TOKEN: ${MANAGE_MEALS_COOKIE_ACCESS_TOKEN}
      COOKIE_REFRESH_TOKEN: ${MANAGE_MEALS_COOKIE_REFRESH_TOKEN}
      COOKIE_ACCESS_TOKEN_EXPIRE_SEC: ${MANAGE_MEALS_COOKIE_ACCESS_TOKEN_EXPIRE_SEC}
      COOKIE_REFRESH_TOKEN_EXPIRE_SEC: ${MANAGE_MEALS_COOKIE_REFRESH_TOKEN_EXPIRE_SEC}
      ORIGIN: ${MEALS_URL}
      PASSWORD_MIN_LENGTH: ${MANAGE_MEALS_PASSWORD_MIN_LENGTH}
      PUBLIC_MAIN_TITLE: ${MANAGE_MEALS_TITLE}
    image: ghcr.io/managemeals/manage-meals-web:${LATEST_VERSION}
    labels:
      <<: *label-wud-latest
      wud.display.icon: 'sh-mealie'
      wud.display.name: 'ManageMeals Web'
      wud.link.template: 'https://github.com/managemeals/manage-meals-web/pkgs/container/manage-meals-web'
    volumes:
      - ${DIR_LOCALTIME}:${DIR_LOCALTIME}:ro

  mongodb:
    <<: [*basic, *network-zero, *restart-always]
    container_name: ${MONGODB_NAME}
    image: mongo:${MONGODB_VERSION}
    labels:
      <<: *label-wud-semver
      wud.display.icon: 'sh-mongodb'
      wud.display.name: 'MongoDB'
      wud.link.template: 'https://hub.docker.com/_/mongo/tags'
    volumes:
      - ${DIR_APPDATA}/mongodb:/data/db
      - ${DIR_LOCALTIME}:${DIR_LOCALTIME}:ro

  typesense:
    <<: [*basic, *network-zero, *restart-always]
    command: "--data-dir /data --api-key=${TYPESENSE_API_KEY} --enable-cors"
    container_name: ${TYPESENSE_NAME}
    image: typesense/typesense:${TYPESENSE_VERSION}
    labels:
      <<: *label-wud-2-semver
      wud.display.icon: 'https://typesense.org/typesense-logo-dark.svg'
      wud.display.name: 'typesense'
      wud.link.template: 'https://hub.docker.com/r/typesense/typesense/tags'
    volumes:
      - ${DIR_APPDATA}/typesense/data:/data
      - ${DIR_LOCALTIME}:${DIR_LOCALTIME}:ro

  valkey:
    <<: [*basic, *network-zero, *restart-always]
    container_name: ${VALKEY_NAME}
    image: valkey/valkey:${VALKEY_VERSION}
    labels:
      <<: *label-wud-semver
      wud.display.icon: 'sh-valkey'
      wud.display.name: 'Valkey'
      wud.link.template: 'https://hub.docker.com/r/valkey/valkey/tags'
    volumes:
      - ${DIR_LOCALTIME}:${DIR_LOCALTIME}:ro
```

Logs API
```bash
2025/05/28 02:22PM 30 pid=1 hostname=zero reqId=req-f url=/v1/auth/login id=req-f msg=received request
2025/05/28 02:22PM 30 pid=1 hostname=zero reqId=req-f url=/v1/auth/login statusCode=200 msg=request completed
```

Thanks for the help
